spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fly-core
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
        - id: chat-service
          uri: http://localhost:8070
          predicates:
            - Path=/socket/**
            - Path=/ws/**


server:
  port: 8758


